name: reddit_words
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - faiss-cpu=1.7.0
  - pip:
    - black==21.5b1
    - flask==2.0.1
    - gunicorn==20.1.0
    - sense2vec==2.0.0
    - spacy==3.0.6
    - pytest==6.2.4